import { expect, test } from '@playwright/test'

const storageKey = 'microbit-homework:attempt:v2:buttons-led-v1'
const openLesson = async (page: import('@playwright/test').Page) => {
  await page.getByRole('link', { name: /Buttons & LED Display/ }).click()
  await expect(page).toHaveURL(/#\/lesson\/buttons-led-v1$/)
}

test.beforeEach(async ({ page }) => {
  await page.goto('/#/')
  await page.evaluate(() => localStorage.clear())
  await page.reload()
})

test('shows the branded mission library and a stable lesson link', async ({ page }) => {
  await expect(page.getByRole('heading', { name: 'Pick your next challenge' })).toBeVisible()
  await expect(page.getByAltText('Bricks 4 Kidz')).toBeVisible()
  await expect(page.getByAltText('LogicLab')).toBeVisible()
  await expect(page.locator('.lesson-card')).toHaveCount(4)
  await expect(page.getByText('Coming soon')).toHaveCount(3)
  await openLesson(page)
  await page.reload()
  await expect(page.getByLabel('Inventor name')).toBeVisible()
})

test('validates name, persists progress, submits weighted answers and retries', async ({ page }) => {
  await openLesson(page)
  await page.getByRole('button', { name: /Start mission/ }).click()
  await expect(page.getByRole('alert')).toContainText('enter your name')
  await page.getByLabel('Inventor name').fill('Alex')
  await page.getByRole('button', { name: /Start mission/ }).click()
  await page.getByRole('button', { name: /I’m ready/ }).click()
  await page.locator('[data-question="q1"] .choice').nth(0).click()
  await page.locator('[data-question="q2"] .choice').nth(1).click()
  await page.locator('[data-question="q3"] .choice').nth(0).click()
  await page.getByLabel('Function of show icon ♥').selectOption('f-heart')
  await page.getByLabel('Function of clear screen').selectOption('f-clear')
  await page.getByLabel('Function of on button B pressed').selectOption('f-event-b')
  await page.locator('[data-question="q5"] button[aria-label="Move down"]').first().click()
  await page.locator('[data-question="q5"] button[aria-label="Move up"]').nth(1).click()
  await page.locator('[data-question="q6"] .block-bank button').first().dragTo(page.locator('[data-question="q6"] .drop-zone'))
  await page.reload()
  await expect(page.getByText('Inventor Alex')).toBeVisible()
  await page.getByRole('button', { name: /Enter the coding lab/ }).click()
  await page.getByRole('button', { name: /Submit and view results/ }).click()
  await expect(page.getByText('/ 10 points')).toBeVisible()
  await expect(page.getByText('10', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Export result as JSON/ }).click()
  expect((await downloadPromise).suggestedFilename()).toMatch(/^result-MB-.+\.json$/)
  await page.getByRole('button', { name: /Try this mission again/ }).click()
  await expect(page.getByText('Quick review before launch')).toBeVisible()
  const saved = await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!), storageKey)
  expect(saved.answers).toEqual({})
  expect(saved.submittedAt).toBeUndefined()
})

test('supports wrong and unanswered answers with an exact zero score', async ({ page }) => {
  await openLesson(page)
  await page.getByLabel('Inventor name').fill('Bailey')
  await page.getByRole('button', { name: /Start mission/ }).click()
  await page.getByRole('button', { name: /I’m ready/ }).click()
  await page.locator('[data-question="q1"] .choice').nth(1).click()
  await page.getByRole('button', { name: /Enter the coding lab/ }).click()
  await page.getByRole('button', { name: /Submit and view results/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByText('Not answered').first()).toBeVisible()
})

test('supports choose-then-place controls and clearing saved progress', async ({ page }) => {
  await openLesson(page)
  await page.getByLabel('Inventor name').fill('Casey')
  await page.getByRole('button', { name: /Start mission/ }).click()
  await page.getByRole('button', { name: /I’m ready/ }).click()
  const fill = page.locator('[data-question="q6"]')
  await fill.locator('.block-bank button').first().click()
  await expect(fill.getByText('Tap to place the selected block')).toBeVisible()
  await fill.getByRole('button', { name: 'Missing block position' }).click()
  await expect(fill.locator('.drop-zone svg')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Clear progress' }).click()
  await expect(page.getByLabel('Inventor name')).toHaveValue('')
  expect(await page.evaluate((key) => JSON.parse(localStorage.getItem(key)!).answers, storageKey)).toEqual({})
})

test('loads the official MakeCode iframe or exposes the network fallback', async ({ page }) => {
  await openLesson(page)
  await page.getByLabel('Inventor name').fill('Drew')
  await page.getByRole('button', { name: /Start mission/ }).click()
  await page.getByRole('button', { name: /I’m ready/ }).click()
  await page.getByRole('button', { name: /Enter the coding lab/ }).click()
  await expect(page.getByTitle('Microsoft MakeCode editor for micro:bit')).toBeVisible()
  const makeCodeStatus = page.getByText(/MakeCode connected|No response from MakeCode/)
  await expect(makeCodeStatus).toBeVisible({ timeout: 12_000 })
  console.log(`MAKECODE_STATUS=${await makeCodeStatus.innerText()}`)
  await expect(page.getByRole('link', { name: /Open MakeCode in a new tab/ })).toHaveAttribute('target', '_blank')
})

test.describe('tablet', () => {
  test.use({ viewport: { width: 820, height: 1180 } })
  test('has no horizontal overflow and touch-sized controls', async ({ page }) => {
    await expect(page.getByRole('heading', { name: 'Pick your next challenge' })).toBeVisible()
    await openLesson(page)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(overflow).toBe(false)
    expect((await page.getByRole('button', { name: /Start mission/ }).boundingBox())!.height).toBeGreaterThanOrEqual(44)
  })
})
