import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => { await page.goto('/'); await page.evaluate(() => localStorage.clear()); await page.reload() })

test('validates name, persists progress, submits correct weighted answers and retries', async ({ page }) => {
  await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).click()
  await expect(page.getByRole('alert')).toContainText('nhập tên')
  await page.getByLabel('Tên nhà sáng chế').fill('An')
  await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).click()
  await page.getByRole('button', { name: /sẵn sàng/ }).click()
  await page.locator('[data-question="q1"] .choice').nth(0).click()
  await page.locator('[data-question="q2"] .choice').nth(1).click()
  await page.locator('[data-question="q3"] .choice').nth(0).click()
  await page.getByLabel('Chức năng của hiện biểu tượng ♥').selectOption('f-heart')
  await page.getByLabel('Chức năng của xóa màn hình').selectOption('f-clear')
  await page.getByLabel('Chức năng của khi nút B được nhấn').selectOption('f-event-b')
  await page.locator('[data-question="q5"] button[aria-label="Đưa xuống"]').first().click()
  await page.locator('[data-question="q5"] button[aria-label="Đưa lên"]').nth(1).click()
  await page.locator('[data-question="q6"] .block-bank button').first().dragTo(page.locator('[data-question="q6"] .drop-zone'))
  await page.reload()
  await expect(page.getByText('Nhà sáng chế An')).toBeVisible()
  await page.getByRole('button', { name: /Đến phòng thực hành/ }).click()
  await page.getByRole('button', { name: /Nộp bài/ }).click()
  await expect(page.getByText('/ 10 điểm')).toBeVisible()
  await expect(page.getByText('10', { exact: true })).toBeVisible()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: /Xuất kết quả JSON/ }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^ket-qua-MB-.+\.json$/)
  await page.getByRole('button', { name: /Làm lại từ đầu/ }).click()
  await expect(page.getByText('Ôn nhanh trước khi xuất phát')).toBeVisible()
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('microbit-homework:current-attempt:v1')!))
  expect(saved.answers).toEqual({})
  expect(saved.submittedAt).toBeUndefined()
})

test('supports wrong and unanswered answers with exact score', async ({ page }) => {
  await page.getByLabel('Tên nhà sáng chế').fill('Bình')
  await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).click()
  await page.getByRole('button', { name: /sẵn sàng/ }).click()
  await page.locator('[data-question="q1"] .choice').nth(1).click()
  await page.getByRole('button', { name: /Đến phòng thực hành/ }).click()
  await page.getByRole('button', { name: /Nộp bài/ }).click()
  await expect(page.getByText('0', { exact: true })).toBeVisible()
  await expect(page.getByText('Chưa trả lời').first()).toBeVisible()
})

test('supports choose-then-place controls and clearing saved progress', async ({ page }) => {
  await page.getByLabel('Tên nhà sáng chế').fill('Chi')
  await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).click()
  await page.getByRole('button', { name: /sẵn sàng/ }).click()
  const fill = page.locator('[data-question="q6"]')
  await fill.locator('.block-bank button').first().click()
  await expect(fill.getByText('Chạm để đặt khối đã chọn')).toBeVisible()
  await fill.getByRole('button', { name: 'Vị trí đặt khối còn thiếu' }).click()
  await expect(fill.locator('.drop-zone svg')).toBeVisible()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Xóa tiến độ' }).click()
  await expect(page.getByLabel('Tên nhà sáng chế')).toHaveValue('')
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('microbit-homework:current-attempt:v1')!).answers)).toEqual({})
})

test('loads the official MakeCode iframe or exposes the network fallback', async ({ page }) => {
  await page.getByLabel('Tên nhà sáng chế').fill('Dương')
  await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).click()
  await page.getByRole('button', { name: /sẵn sàng/ }).click()
  await page.getByRole('button', { name: /Đến phòng thực hành/ }).click()
  await expect(page.getByTitle('Trình soạn thảo Microsoft MakeCode cho micro:bit')).toBeVisible()
  const makeCodeStatus = page.getByText(/MakeCode đã kết nối|Không nhận được phản hồi từ MakeCode/)
  await expect(makeCodeStatus).toBeVisible({ timeout: 12_000 })
  console.log(`MAKECODE_STATUS=${await makeCodeStatus.innerText()}`)
  await expect(page.getByRole('link', { name: /Mở MakeCode ở tab mới/ })).toHaveAttribute('target', '_blank')
})

test.describe('tablet', () => {
  test.use({ viewport: { width: 820, height: 1180 } })
  test('has no horizontal overflow and touch-sized entry controls', async ({ page }) => {
    await expect(page.getByLabel('Tên nhà sáng chế')).toBeVisible()
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth)
    expect(overflow).toBe(false)
    expect((await page.getByRole('button', { name: /Bắt đầu nhiệm vụ/ }).boundingBox())!.height).toBeGreaterThanOrEqual(44)
  })
})
